// <auto-generated />
namespace Bloomfiy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "202512051109474_InitAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
